### ISSUE TITLE
URL转换问题

### ISSUE THREAD

**Issue by XiaoMouz** [ustc-zzzz/mcbbs-markdown2bbcode-converter#21]
在执行URL转化时出错
eg:
```markdown
[分离](https://baidu.com)
```
被转成了
```BBcode
[size=15px]分离 [size=14px]([/size] [size=13px][font=Monaco,Consolas,'Lucida Console','Courier New',serif]https://baidu.com[/font][/size] [size=14px])[/size] [/size]
```
因此需要重新修改

**Comment by ustc-zzzz** [comment]
![image](https://user-images.githubusercontent.com/8004211/116460854-1bd05480-a89a-11eb-9ad5-c776ba4c05a6.png)

你好，我这里显示的结果是正常的，无法复现上述行为。

方便提供一下你所使用的浏览器和操作系统环境吗？如果浏览器安装有插件，请将插件全部关掉再试。

**Comment by XiaoMouz** [comment]
使用Chrome  90.0.4430.93 x64 运行在Win10专业版20H2 x64环境下
转到Firefox后一切正常，可能是因为部分文件没有成功加载出来的原因，打扰了
