### ISSUE TITLE
换行无效问题

### ISSUE THREAD

**Issue by TartaricAcid** [ustc-zzzz/mcbbs-markdown2bbcode-converter#3]
如图所示，我在使用中发现所有的换行几乎失败，如图所示：

![2018-02-09 21-11-33屏幕截图.png](https://i.loli.net/2018/02/09/5a7d9e1a753dd.png)

![2018-02-09 21-23-07屏幕截图.png](https://i.loli.net/2018/02/09/5a7da0cd21a24.png)

![2018-02-09 21-27-00屏幕截图.png](https://i.loli.net/2018/02/09/5a7da1b97c60e.png)

原文再此：[戳我啊](https://raw.githubusercontent.com/TartaricAcid/tartaricacid.github.io/master/_posts/2017-08-07-CMMDoc.md)

使用系统：`Ubuntu 16.04 LTS`

**Comment by ustc-zzzz** [comment]
唔，看起来mm2bc这边没有什么问题，可能是mm2bc粘贴到mcbbs的时候出现了问题，我回头加个一键复制按钮好了。

**Comment by ustc-zzzz** [comment]
按钮已经加完了
